### ISSUE TITLE
Dashboards: move error

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#12]
when I try to move a dash, an error message appears:

"Coding error detected, it must be fixed by a programmer: Trying to reference an unknown block region region--"

Steps to reproduce:
1) create a dashboard
2) add two dashes 
3) try to move them

**Comment by stefanscholz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboards](https://trello.com/c/1rD6oEiE/105-dashboards)

**Comment by moodledev** [comment]
For some reason Moodle cleans block region names to letters and hyphens only (a-zA-Z). That's why region-<id>-<contextid> is being cleaned to region--

To solve this, I have added a "shortname" field to dashboards. This name must be unique and only contain a-zA-Z, and is used for a unique, compliant block region name.

This is a major change so I apologize if your existing dashboards misplace some blocks. Please pull the latest from both local_dash and block_dash.

**Comment by stefanscholz** [comment]
Great!
