### ISSUE TITLE
Data Source Course: Course ID

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#24]
Can you please add the (technical) course ID as field, too?

I want to use it to construct links like http://dash.bdecent.de/course/edit.php?id=2 in custom templates.

**Comment by moodledev** [comment]
I remove identifier fields when using a layout that supports field visibility/sorting. That's because the ID fields need to come first, and they can't be moved around. (Or disabled)

But this should not impact custom developed dashes. You will have access to all fields in your mustache template, even if they are somehow hidden.

![image](https://user-images.githubusercontent.com/46829091/71020259-99d6f580-20c1-11ea-92eb-f766189760b8.png)

**Comment by stefanscholz** [comment]
Ok, fine for me
