### ISSUE TITLE
Course Context for Dashboards

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#41]
I wanted to test the course context feature of the dashboard.

I configured the dashboard "courses" to be in the course context of "Test Course".

I added a dash with the data source courses and the template figure.

I chose as condition: "current course"

I chose the field "Full name" and expected it to say "Test Course".

Instead, it is empty.

(no matter which field I select)

What did I do wrong or where do I misunderstand the meaning of the course context?

Is it maybe only working for another data source?

**Comment by stefanscholz** [comment]
Note: if I remove "current course", it seems to work. Is that expected?

**Comment by moodledev** [comment]
I followed your steps and it's working as expected on my dashboard.

![image](https://user-images.githubusercontent.com/46829091/71601667-1c2bd480-2b1a-11ea-9dc2-1dd42b2c05fb.png)

Here's my preferences:

![image](https://user-images.githubusercontent.com/46829091/71601694-349bef00-2b1a-11ea-9ff2-1ca6fedc72d1.png)

The figure layouts take the first row returned, so perhaps it's working without the "Current course" condition is because it's returning all courses and grabbing the first one.

Are you sure the dashboard is set to the course context?

**Comment by stefanscholz** [comment]
I think I know the reason; I probably tried to test this by changing the course context from one course to another. I was expecting to see a changed course full name after changing the course context from "test course 1" to "test course 2", resulting in 

first "test course 1" being displayed 

and then, after changing it to the test course 2 context, expecting

then "test course 2" being displayed 
--> but instead, the dashboard is completely empty. probably related to the other issue I posted about chaning shortnames of dashboards resulting in empty dashboards.

(as long as I do not change the course context, it seems to work as expected)
