### ISSUE TITLE
Duplicated (multiple) entries in user data source 

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#52]
Using users data source, I see some users several times. This has (I believe) not happened until today.

![15768603211735263234175534661983](https://user-images.githubusercontent.com/3414705/71269836-84c3c600-2350-11ea-8e6a-7517aaa07c1d.jpg)

![1576860347401254874872408929184](https://user-images.githubusercontent.com/3414705/71269856-9016f180-2350-11ea-9492-d84eb8453cde.jpg)

![15768603802768687325876996590761](https://user-images.githubusercontent.com/3414705/71269908-a755df00-2350-11ea-8342-11fcd32e5401.jpg)

Also applies to the group filter (but that has been reported already)

**Comment by moodledev** [comment]
The cause of this is because a user may have multiple groups or enrollments, which returns multiple records. I  implemented a group by feature that will group by the first identifier in a data source. Therefore, the user data source is now grouping by the user ID. This is closer to what you're expecting. Please try it out and let me know what you think.

**Comment by stefanscholz** [comment]
looks good!
